<a href="https://colab.research.google.com/github/Rahulgarg95/pytorch_jovian/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1bhcWOHT4J4zU_NTNMO1_eAzq4xU5n9KC')

# 5 Pytorch Basic Functions Every Developer Should Know About

PyTorch is a Python-based scientific computing package that uses the power of graphics processing units. It is also one of the preferred deep learning research platforms built to provide maximum flexibility and speed. It is known for providing two of the most high-level features; namely, tensor computations with strong GPU acceleration support and building deep neural networks on a tape-based autograd systems.

- torch.from_numpy()
- torch.chunk()
- torch.stack()
- torch.addcmul()
- torch.where()

Before we begin, let's install and import PyTorch

In [32]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [33]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.from_numpy()

A Pytorch method to converts a numpy array to a tensor.
The returned tensor(output) and ndarray(input) share the same memory. The returned tensor is not resizable.

In [34]:
# Example 1 - working
x=np.array([1,2,3,4,5,6,7,8,9])
print(type(x))
print('Numpy Array ==> ',x,type(x[0]))

t=torch.from_numpy(x)
print(type(t))
print('New Tensor ==> ',t,type(t[0].item()))

<class 'numpy.ndarray'>
Numpy Array ==>  [1 2 3 4 5 6 7 8 9] <class 'numpy.int64'>
<class 'torch.Tensor'>
New Tensor ==>  tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) <class 'int'>


The above example demonstrates how a 1-D numpy array is converted to tensor using simple from_numpy function.
As can be seen the datatype remains the same.

In [35]:
# Example 2 - working
x=np.array([[1,2.5,3],[4,5,6]])
print(type(x))
print('Numpy Array ==> ',x,type(x[0][0]))

t=torch.from_numpy(x)
print(type(t))
print('New Tensor ==> ',t,type(t[0][0].item()))

<class 'numpy.ndarray'>
Numpy Array ==>  [[1.  2.5 3. ]
 [4.  5.  6. ]] <class 'numpy.float64'>
<class 'torch.Tensor'>
New Tensor ==>  tensor([[1.0000, 2.5000, 3.0000],
        [4.0000, 5.0000, 6.0000]], dtype=torch.float64) <class 'float'>


The above example demontrates converting a numpy 2-D array to tensor. Even if one element is float the whole array is converted to float and the same populates to tensor created.

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
x=np.array(['a',1,2])
print(type(x))
print('Numpy Array ==> ',x,type(x))

t=torch.from_numpy(x)
print(t)

<class 'numpy.ndarray'>
Numpy Array ==>  ['a' '1' '2'] <class 'numpy.ndarray'>


TypeError: ignored

In above example we created a numpy arraye with a combination of string and numbers. torch.from_numpy method breaks in this case and raises exception as this method from excepts int,float,bool & complex datatypes.

The function can be extensively used as multiple libraries like scipy and statsmodel are compatible with numpy arrays, which provides pytorch users with a power to use these libraries after converting tensor to numpy array.As the memory location remains same hence it is performance efficient as well.

In [37]:
!pip install jovian --upgrade --quiet

In [38]:
import jovian

In [39]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rahulgarg95/01-tensor-operations


'https://jovian.ai/rahulgarg95/01-tensor-operations'

## torch.chunk()

The function is used to divide a tensor into multiple smaller tensors as per the chunks count entered by the user and along the specified axis.

In [48]:
# Example 1 - working
t=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t)

output=torch.chunk(t,3,0)
print(type(output),output)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
<class 'tuple'> (tensor([[1, 2, 3]]), tensor([[4, 5, 6]]), tensor([[7, 8, 9]]))


The above exmple illustrates a typical example of torch.chunk here we are dividing tensor into 3 chunks along the row axis.

The output returns tuple of 3 1-D tensors.

In [55]:
# Example 2 - working
t=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t)

output=torch.chunk(t,2,1)
print(type(output),output)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
<class 'tuple'> (tensor([[1, 2],
        [4, 5],
        [7, 8]]), tensor([[3],
        [6],
        [9]]))
tensor([[1, 2],
        [4, 5],
        [7, 8]])


In the above example we enchanced the previous example and tried to get chunks along the column axis. Also we provided number of chunks a number which does not given modulus of len as 0. Here we see the first chunk contains two columns and other one containing only 1.

In [65]:
# Example 3 - breaking (to illustrate when it breaks)
t=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t)

try:
  output=torch.chunk(t,1,2)
  print(type(output),output)
except Exception as e:
  print('Error: ',e)


t=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(t)

output=torch.chunk(t,1,2)
print(type(output),output)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Dimension out of range (expected to be in range of [-2, 1], but got 2)
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
<class 'tuple'> (tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]),)


The above example illustrates the breaking point of chunk function. The axis value should be in range[-n,n-1] as specified in error. Hence while working with multiple dimension matrixes we need to keep this into account.
As same arguments work with 3-D but gives error with 2-D.

tensor.chunk() can be used widely to divide data into test and training sets and then apply operations seperately on multiple chunks.

In [66]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rahulgarg95/01-tensor-operations


'https://jovian.ai/rahulgarg95/01-tensor-operations'

## torch.stack()

Concatenates a sequence of tensors along a new dimension.

In [73]:
# Example 1 - working
t1=torch.tensor([[1,2,3],[4,5,6]])
print('Tensor1 ==> ',t1, t1.shape)

t2=torch.tensor([[10,20,30],[40,50,60]])
print('Tensor1 ==> ',t2, t2.shape)

t=torch.stack((t1,t2))
print('Stacked Tensor ==> ', t, t.shape)

Tensor1 ==>  tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
Tensor1 ==>  tensor([[10, 20, 30],
        [40, 50, 60]]) torch.Size([2, 3])
Stacked Tensor ==>  tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 20, 30],
         [40, 50, 60]]]) torch.Size([2, 2, 3])


In the above example we demonstrated a basic example of stacking where two 2-D tensors of shape (2,3) are stacked to give a 3-D tensor of size (2,2,3). The stacking is done along the row axis.

In [76]:
# Example 2 - working
t1=torch.tensor([[1,2,3],[4,5,6]])
print('Tensor1 ==> ',t1, t1.shape)

t2=torch.tensor([[10,20,30],[40,50,60]])
print('Tensor1 ==> ',t2, t2.shape)

torch.stack((t1,t2),1,out=t)
print('Stacked Tensor ==> ', t, t.shape)

Tensor1 ==>  tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
Tensor1 ==>  tensor([[10, 20, 30],
        [40, 50, 60]]) torch.Size([2, 3])
Stacked Tensor ==>  tensor([[[ 1,  2,  3],
         [10, 20, 30]],

        [[ 4,  5,  6],
         [40, 50, 60]]]) torch.Size([2, 2, 3])


The above example enhances the previous example by stacking the tensors along a different axis also we implicity define the output tensor where the output is saved.

In [77]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 1 - working
t1=torch.tensor([[1,2,3],[4,5,6]])
print('Tensor1 ==> ',t1, t1.shape)

t2=torch.tensor([[10,20,30]])
print('Tensor1 ==> ',t2, t2.shape)

t=torch.stack((t1,t2))
print('Stacked Tensor ==> ', t, t.shape)

Tensor1 ==>  tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
Tensor1 ==>  tensor([[10, 20, 30]]) torch.Size([1, 3])


RuntimeError: ignored

The above example illustrates where torch.stack() breaks or gives an exception. The tensors should be of same shape along the axis for stacking to happen otherwise error is thrown.

torch.stack function will be used in scenarios where a new dimension needs to be added to existing tensor. As tensor.cat function only appends the data along with the existing axis.

In [78]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rahulgarg95/01-tensor-operations


'https://jovian.ai/rahulgarg95/01-tensor-operations'

## torch.addcmul()

The function performs element wise multiplication of tensor1 and tensor2, multiply the result with a specified scalar value and adding the result with input tensors.

In [88]:
# Example 1 - working
t = torch.randn(3, 2)
print('Input Tensor ==> \n',t)

t1 = torch.randn(3,2)
print('\nFirst Tensor ==> \n',t1)

t2 = torch.randn(3,2)
print('\nSecond Tensor ==> \n',t2)

result=torch.addcmul(t,t1,t2,value=10)
print('\nResultant Tensor ==> \n',result)

Input Tensor ==> 
 tensor([[-0.9881, -0.1219],
        [ 1.1055, -0.6201],
        [-1.5837,  0.9890]])

First Tensor ==> 
 tensor([[-0.6789, -1.7465],
        [ 0.8081,  1.4946],
        [-0.2175, -0.9214]])

Second Tensor ==> 
 tensor([[ 0.1365,  0.0705],
        [ 0.8872, -1.0354],
        [ 0.8538, -0.5540]])

Resultant Tensor ==> 
 tensor([[ -1.9147,  -1.3540],
        [  8.2752, -16.0953],
        [ -3.4407,   6.0937]])


The above example initialzes input tensor and other two tensors which are supplied as arguments to torch.addcmul() function, also a constant value of 10 is provided which is contributing to the above result.

In [91]:
# Example 2 - working
t = torch.randn(1, 2)
print('Input Tensor ==> \n',t)

t1 = torch.randn(3,2)
print('\nFirst Tensor ==> \n',t1)

t2 = torch.randn(3,1)
print('\nSecond Tensor ==> \n',t2)

result=torch.addcmul(t,t1,t2,value=11)
print('\nResultant Tensor ==> \n',result)

Input Tensor ==> 
 tensor([[0.4832, 1.6053]])

First Tensor ==> 
 tensor([[ 0.7445, -1.1826],
        [ 0.0850, -1.8269],
        [ 0.0704, -0.1180]])

Second Tensor ==> 
 tensor([[ 1.5051],
        [-1.4491],
        [ 0.6629]])

Resultant Tensor ==> 
 tensor([[ 12.8103, -17.9750],
        [ -0.8711,  30.7267],
        [  0.9967,   0.7448]])


The above example builts on top of previous example were we have changed the dimentions of different tensors and then add addcmul operation.

The point here to be noted is no of columns should be same in input and other tensors.

In [92]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 2 - working
t = torch.randn(1, 3)
print('Input Tensor ==> \n',t)

t1 = torch.randn(3,2)
print('\nFirst Tensor ==> \n',t1)

t2 = torch.randn(3,1)
print('\nSecond Tensor ==> \n',t2)

result=torch.addcmul(t,t1,t2,value=11)
print('\nResultant Tensor ==> \n',result)

Input Tensor ==> 
 tensor([[-1.7170, -1.0950,  0.1610]])

First Tensor ==> 
 tensor([[-0.8944,  1.2394],
        [-1.6409, -1.3244],
        [-1.9642, -0.2736]])

Second Tensor ==> 
 tensor([[ 0.8995],
        [ 0.4175],
        [-0.0844]])


RuntimeError: ignored

The above example illustrate the point where the above example throws an exception as the dimension of tensors do not align with each other.

tensor.addcmul function can be quite helpful during forward propogation of deep neural networks.

In [93]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rahulgarg95/01-tensor-operations


'https://jovian.ai/rahulgarg95/01-tensor-operations'

## torch.where()

torch.where() function is used to apply a condition statement on input tensor and populate values to the same accordingly.

torch.where(condition,x,y) => If condition is met, value of x is replaced otherwise value of y is replaced.

In [98]:
# Example 1 - working
t1 = torch.randn(3, 2)
print('Tensor1 ==> \n',t1)

t2 = torch.ones(3, 2)
print('\nTensor2 ==> \n',t2)

print('\nFinal Tensor ==> \n',torch.where(t1 > 0, t1, t2))

Tensor1 ==> 
 tensor([[ 1.5462,  0.1570],
        [ 0.0845, -0.5417],
        [ 0.4771, -0.2600]])

Tensor2 ==> 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Final Tensor ==> 
 tensor([[1.5462, 0.1570],
        [0.0845, 1.0000],
        [0.4771, 1.0000]])


The above example illustrates the use of torch.where function where all the elements in t1 having value greater than 0 is replaces by the one's in t2.

In [105]:
# Example 2 - working
t1 = torch.randn((3, 2),dtype=torch.double)
print('Tensor1 ==> \n',t1)

t2 = torch.ones(3, 2)
print('\nTensor2 ==> \n',t2)

print('\nFinal Tensor ==> \n',torch.where(t1 > 0, t1, 100.))

Tensor1 ==> 
 tensor([[ 0.7894, -0.5913],
        [ 0.2329,  0.0363],
        [-0.1116,  0.8967]], dtype=torch.float64)

Tensor2 ==> 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Final Tensor ==> 
 tensor([[7.8940e-01, 1.0000e+02],
        [2.3292e-01, 3.6292e-02],
        [1.0000e+02, 8.9668e-01]], dtype=torch.float64)


The above example illustrates the use of scalar value instead of another tensor.

In [106]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 2 - working
t1 = torch.randn((3, 2))
print('Tensor1 ==> \n',t1)

t2 = torch.ones(3, 2)
print('\nTensor2 ==> \n',t2)

print('\nFinal Tensor ==> \n',torch.where(t1 > 0, t1, 100.))

Tensor1 ==> 
 tensor([[ 2.4679,  0.7438],
        [-0.7768,  0.3895],
        [ 0.1333, -1.5188]])

Tensor2 ==> 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


RuntimeError: ignored

The above examples illustrates the point where torch.where function can throw an error if datatypes do not where. Better to explicity define dtype where initializing the tensor.

The above function can be used to perform multiple operations and apply user defined conditions and create a customised tensor accordingly.

In [107]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rahulgarg95/01-tensor-operations


'https://jovian.ai/rahulgarg95/01-tensor-operations'

## Conclusion

We have covered 5 different basic functions of pytorch which can help you to get started in pytorch and apply basic idea of how this framework works.

Please check out below reference links to explore above functions or find more pytorch functions to play wth them.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* https://www.kite.com/python/docs/*
* http://geeksforgeeks.org/

In [108]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rahulgarg95/01-tensor-operations


'https://jovian.ai/rahulgarg95/01-tensor-operations'